# Generated by Django 2.1.5 on 2020-05-29 07:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creamprod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Serial_White_ExLM', models.PositiveIntegerField()),
                ('Serial_White_Gold_SWM', models.PositiveIntegerField()),
                ('Soft_Flower_LL', models.PositiveIntegerField()),
                ('Soft_Flower_FC', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('emp_code', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Soapprod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Serial_White_Guava', models.PositiveIntegerField()),
                ('Serial_White_Premium', models.PositiveIntegerField()),
                ('Soft_Flower_Body_Wash', models.PositiveIntegerField()),
                ('Soft_Flower_Fresh', models.PositiveIntegerField()),
                ('Soft_Flower_Orange_Lightening', models.PositiveIntegerField()),
                ('Soft_Flower_Carot_Lightening', models.PositiveIntegerField()),
                ('Soft_Flower_Papaya_Extract', models.PositiveIntegerField()),
                ('Soft_Flower_Extra_Lightening', models.PositiveIntegerField()),
                ('Serial_White_Papaya_4in1', models.PositiveIntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Staffinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=5)),
                ('staff_name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Staffrec',
            fields=[
                ('staffno', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=35)),
                ('sex', models.CharField(max_length=7)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_site', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Creamsales',
            fields=[
                ('creamprod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Creamprod')),
                ('cream_marketer_status', models.CharField(choices=[('M', 'Marketers'), ('D1', 'Distributor 1'), ('D2', 'Distributor 2'), ('D3', 'Distributor 3')], max_length=1)),
            ],
            bases=('pages.creamprod',),
        ),
        migrations.CreateModel(
            name='Soapsales',
            fields=[
                ('soapprod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Soapprod')),
                ('soap_marketer_status', models.CharField(choices=[('M', 'Marketers'), ('D1', 'Distributor 1'), ('D2', 'Distributor 2'), ('D3', 'Distributor 3')], max_length=1)),
            ],
            bases=('pages.soapprod',),
        ),
    ]
