# Generated by Django 2.1.5 on 2020-05-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffrec',
            old_name='staffno',
            new_name='staff_id',
        ),
    ]
