# Generated by Django 2.1.5 on 2020-05-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200529_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creamsales',
            name='cream_marketer_status',
            field=models.CharField(choices=[('M', 'Marketers'), ('DA', 'Distributor_A'), ('DB', 'Distributor_B'), ('DC', 'Distributor_C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='soapsales',
            name='soap_marketer_status',
            field=models.CharField(choices=[('M', 'Marketers'), ('DA', 'Distributor_A'), ('DB', 'Distributor_B'), ('DC', 'Distributor_C')], max_length=1),
        ),
    ]
