# Generated by Django 2.1.5 on 2020-05-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200529_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creamsales',
            name='cream_marketer_status',
            field=models.CharField(choices=[('M', 'Marketers'), ('D', 'Distributor'), ('DB', 'Distributor_B'), ('DC', 'Distributor_C')], max_length=1),
        ),
        migrations.AlterField(
            model_name='soapsales',
            name='soap_marketer_status',
            field=models.CharField(choices=[('M', 'Marketers'), ('D', 'Distributor'), ('DB', 'Distributor_B'), ('DC', 'Distributor_C')], max_length=1),
        ),
    ]
